### PR TITLE
Fixed jQuery UI error #175

### LINKED ISSUE #175: JS error on latest master
Once on b8e8326, if I open the widget in the admin, the sortable feature is broken and I see the following errors in the JS console:

jquery-ui.js:6 Uncaught TypeError: Cannot read property 'ui' of undefined
jquery.js:4055 Uncaught TypeError: ul.sortable is not a function

Screenshot from 2020-12-02 20-19-29

If I reset to the previous commit I don't see the error, hence I think it was inadvertently introduced in https://github.com/jazzband/django-sortedm2m/pull/170.

@amirouche @clintonb @auvipy is anybody getting this error? Have you tried the latest master in one of your applications?

### PR DESCRIPTION
**Pull request by nemesisdesign**
Fixed jQuery UI error #175

Reintroduced 3 lines which were removed in #170 but
should be reintroduced for backward compatibility.

Fixes #175.

### CODE REVIEW

**Comment by amirouche** [comment]
@nemesisdesign can you replace the ternary comparison at the following line:

https://github.com/jazzband/django-sortedm2m/blob/066b87b352910adcbe524740bb3c300100a18df2/sortedm2m/static/sortedm2m/widget.js#L153

With `jQuery`. Otherwise LGTM :+1:

**Comment by nemesisdesign** [comment]
> @nemesisdesign can you replace the ternary comparison at the following line:
> 
> https://github.com/jazzband/django-sortedm2m/blob/066b87b352910adcbe524740bb3c300100a18df2/sortedm2m/static/sortedm2m/widget.js#L153
> 
> With `jQuery`. Otherwise LGTM

@amirouche done.

**Review by clintonb — APPROVED** [review]

**Comment by nemesisdesign** [comment]
Not sure why this job is failing https://travis-ci.org/github/jazzband/django-sortedm2m/jobs/749661654, looks unrelated to the patch.

**Comment by nemesisdesign** [comment]
@clintonb @amirouche ping

**Comment by nemesisdesign** [comment]
Sup?

**Comment by clintonb** [comment]
Sorry for the delay. I fixed the pylint error with https://github.com/jazzband/django-sortedm2m/pull/178. Rebasing should fix the build error.
